# Generated by Django 4.0.4 on 2023-01-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='attachment_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
