# Generated by Django 4.0.4 on 2023-01-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_school_attachment_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='published_datetime',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
