# Generated by Django 4.0.4 on 2023-01-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_school_published_datetime_alter_school_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='attachment_list',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='body',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='published_datetime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='url',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
