# Generated by Django 4.0.4 on 2023-01-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_school_attachment_list_alter_school_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='attachment_list',
            field=models.CharField(blank=True, default='empty', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='body',
            field=models.CharField(blank=True, default='empty', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='published_datetime',
            field=models.CharField(blank=True, default='empty', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='title',
            field=models.CharField(blank=True, default='empty', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='url',
            field=models.CharField(blank=True, default='empty', max_length=900, null=True),
        ),
    ]
