# Generated by Django 4.0.4 on 2023-01-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_blogdata_alter_school_attachment_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='body',
            field=models.TextField(blank=True, default='empty', null=True),
        ),
    ]
