# Generated by Django 4.0.4 on 2023-01-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_school_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parse_type', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=900, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('published_datetime', models.DateTimeField(blank=True, null=True)),
                ('attachment_list', models.TextField(blank=True, default='empty', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogData',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
